# Generated by Django 4.1.7 on 2023-03-30 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="finance",
            old_name="income_spend",
            new_name="finance_status",
        ),
    ]
