# Generated by Django 4.1.7 on 2023-03-30 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0002_rename_income_spend_finance_finance_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="finance",
            name="amount",
            field=models.FloatField(default=0),
        ),
    ]
