# Generated by Django 4.1.7 on 2023-04-10 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("finances", "0004_finance_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finance",
            name="date_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
