# Generated by Django 4.1.7 on 2023-04-20 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0002_telegramuser_delete_usertelegram"),
        ("finances", "0005_alter_finance_date_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="finance",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.telegramuser",
            ),
        ),
    ]
